import type { GuidelineDefinition, GuidelineDefinitionItem } from "./types";
import { regexMatcher } from "./utils";

export const CONSORT_ITEMS: GuidelineDefinitionItem[] = [
  {
    itemNumber: 1,
    name: "Trial Identification",
    section: "Title/Abstract",
    description: "Identification as a randomised trial in the title or abstract",
    detector: regexMatcher(/\b(randomised|randomized|clinical trial|controlled trial|rct)\b/i, "abstract"),
    recommendationIfAbsent: "State that the investigation is a randomized controlled trial in the title and abstract.",
  },
  {
    itemNumber: 2,
    name: "Trial Design",
    section: "Methods",
    description: "Description of trial design (such as parallel, factorial, crossover) including allocation ratio",
    detector: regexMatcher(/\b(parallel-group|crossover|factorial|allocation ratio|1:1 ratio|2:1)\b/i, "methods"),
    recommendationIfAbsent: "Specify the trial design framework and allocation ratio (e.g. 1:1 parallel group).",
  },
  {
    itemNumber: 3,
    name: "Eligibility Criteria",
    section: "Methods",
    description: "Eligibility criteria for participants and settings and locations where data were collected",
    detector: regexMatcher(/\b(inclusion criteria|exclusion criteria|eligible patients|recruited at)\b/i, "methods"),
    recommendationIfAbsent: "Itemize all clinical inclusion/exclusion criteria.",
  },
  {
    itemNumber: 4,
    name: "Interventions",
    section: "Methods",
    description: "The interventions for each group with sufficient details to allow replication, including placebo/control",
    detector: regexMatcher(/\b(administered|dosage|dose of|placebo|control group|intervention group|regimen)\b/i, "methods"),
    recommendationIfAbsent: "Detail intervention dosage, route, administration timing, and comparator specifications.",
  },
  {
    itemNumber: 5,
    name: "Primary & Secondary Outcomes",
    section: "Methods",
    description: "Completely defined pre-specified primary and secondary outcome measures",
    detector: regexMatcher(/\b(primary outcome|primary endpoint|secondary outcomes|secondary endpoints)\b/i, "methods"),
    recommendationIfAbsent: "Distinguish primary and secondary clinical endpoints with measurement time points.",
  },
  {
    itemNumber: 6,
    name: "Sample Size Determination",
    section: "Methods",
    description: "How sample size was determined, power, effect size assumed",
    detector: regexMatcher(/\b(sample size was calculated|power of 80%|power of 90%|two-sided alpha|detect a difference of)\b/i, "methods"),
    recommendationIfAbsent: "Report the statistical power, expected effect size, and sample size formula used.",
  },
  {
    itemNumber: 7,
    name: "Random Sequence Generation",
    section: "Methods",
    description: "Method used to generate the random allocation sequence",
    detector: regexMatcher(/\b(computer-generated random|random number table|permuted block|block randomization|stratified randomization)\b/i, "methods"),
    recommendationIfAbsent: "Describe the exact algorithm or protocol used to generate the randomization sequence.",
  },
  {
    itemNumber: 8,
    name: "Allocation Concealment",
    section: "Methods",
    description: "Mechanism used to implement the random allocation sequence",
    detector: regexMatcher(/\b(allocation concealment|sequentially numbered|opaque sealed envelopes|central web-based|interactive voice response)\b/i, "methods"),
    recommendationIfAbsent: "Explain the allocation concealment mechanism preventing prior knowledge of assignment.",
  },
  {
    itemNumber: 9,
    name: "Blinding / Masking",
    section: "Methods",
    description: "Who was blinded after assignment to interventions (participants, providers, outcome assessors)",
    detector: regexMatcher(/\b(double-blind|triple-blind|single-blind|blinded to treatment|masked|identical placebo)\b/i, "methods"),
    recommendationIfAbsent: "State clearly who was blinded to allocation (participants, care providers, outcome evaluators).",
  },
  {
    itemNumber: 10,
    name: "Statistical Analysis Methods",
    section: "Methods",
    description: "Statistical methods used to compare groups for primary and secondary outcomes",
    detector: regexMatcher(/\b(intention-to-treat|per-protocol|chi-square|student's t-test|hazard ratio|log-rank)\b/i, "methods"),
    recommendationIfAbsent: "Specify intention-to-treat vs per-protocol analysis strategy.",
  },
  {
    itemNumber: 11,
    name: "Participant Flow & Attrition",
    section: "Results",
    description: "For each group, the numbers of participants randomly assigned, receiving intervention, and analysed",
    detector: regexMatcher(/\b(consort flow|randomly assigned to|assigned to receive|discontinued intervention|analyzed for primary outcome)\b/i, "results"),
    recommendationIfAbsent: "Provide a CONSORT flow diagram or textual account of flow through each trial arm.",
  },
  {
    itemNumber: 12,
    name: "Baseline Demographic Data",
    section: "Results",
    description: "A table showing baseline demographic and clinical characteristics for each group",
    detector: regexMatcher(/\b(table 1|baseline characteristics|demographic data|age, sex)\b/i, "results"),
    recommendationIfAbsent: "Include a Table 1 comparing baseline characteristics across trial groups.",
  },
  {
    itemNumber: 13,
    name: "Outcomes & Estimation",
    section: "Results",
    description: "For each primary and secondary outcome, results for each group, and the estimated effect size and precision",
    detector: regexMatcher(/\b(relative risk|odds ratio|mean difference|confidence interval|p-value|hazard ratio)\b/i, "results"),
    recommendationIfAbsent: "Report effect sizes with 95% confidence intervals for every stated endpoint.",
  },
  {
    itemNumber: 14,
    name: "Adverse Events & Harms",
    section: "Results",
    description: "All important harms or unintended effects in each group",
    detector: regexMatcher(/\b(adverse event|serious adverse event|safety profile|side effects|toxicity|tolerability)\b/i, "results"),
    recommendationIfAbsent: "Document all observed adverse events, toxicities, and harms by group.",
  },
  {
    itemNumber: 15,
    name: "Trial Registration & Ethics",
    section: "Back Matter",
    description: "Registration number and name of trial registry, ethics committee approval",
    detector: regexMatcher(/\b(clinicaltrials\.gov|nct\d{8}|isrctn|institutional review board|irb approval|ethics committee)\b/i),
    recommendationIfAbsent: "Disclose the public clinical trial registration ID and IRB ethics committee approval number.",
  },
];

export const consortGuideline: GuidelineDefinition = {
  id: "consort",
  name: "CONSORT 2010 (Randomized Controlled Trials)",
  standardType: "Randomized Controlled Trials & Interventions",
  standardVersion: "CONSORT 2010",
  standardUrl: "https://www.consort-statement.org/",
  itemSetScope: "core_subset",
  itemSetSize: 25,
  items: CONSORT_ITEMS,
};
