import type { GuidelineDefinition, GuidelineDefinitionItem } from "./types";
import { regexMatcher } from "./utils";

export const PRISMA_ITEMS: GuidelineDefinitionItem[] = [
  {
    itemNumber: 1,
    name: "Title Identification",
    section: "Title/Abstract",
    description: "Identify the report as a systematic review or meta-analysis in title or abstract",
    detector: regexMatcher(/\b(systematic review|meta-analysis|systematic literature review)\b/i, "abstract"),
    recommendationIfAbsent: "Identify the report explicitly as a systematic review or meta-analysis in title or abstract.",
  },
  {
    itemNumber: 2,
    name: "Structured Abstract",
    section: "Abstract",
    description: "Provide a structured abstract covering background, methods, results, and discussion",
    detector: regexMatcher(/\b(background|objective|methods|results|conclusions?)\b/i, "abstract"),
    recommendationIfAbsent: "Structure the abstract explicitly into Background, Methods, Results, and Conclusions.",
  },
  {
    itemNumber: 3,
    name: "Rationale",
    section: "Introduction",
    description: "Describe the rationale for the review in the context of what is already known",
    detector: regexMatcher(/\b(rationale|prior systematic review|need for this review|unresolved questions|knowledge gap)\b/i, "introduction"),
    recommendationIfAbsent: "Describe the scientific rationale for this review in the context of current literature.",
  },
  {
    itemNumber: 4,
    name: "Objectives & Framework",
    section: "Introduction",
    description: "Provide an explicit statement of the question(s) being addressed using PICO or similar framework",
    detector: regexMatcher(/\b(objective|research question|pico|aim of this review|we systematically evaluated)\b/i, "introduction"),
    recommendationIfAbsent: "State explicit review questions using the PICO framework (population, intervention, comparator, outcome).",
  },
  {
    itemNumber: 5,
    name: "Eligibility Criteria",
    section: "Methods",
    description: "Specify the inclusion and exclusion criteria for the review and how studies were grouped",
    detector: regexMatcher(/\b(inclusion criteria|exclusion criteria|eligibility criteria|studies were eligible)\b/i, "methods"),
    recommendationIfAbsent: "Itemize explicit study eligibility criteria (inclusion and exclusion rules).",
  },
  {
    itemNumber: 6,
    name: "Information Sources & Search Dates",
    section: "Methods",
    description: "Specify all databases, registers, websites, and date ranges searched",
    detector: regexMatcher(/\b(pubmed|medline|embase|web of science|scopus|cochrane|searched from|search date)\b/i, "methods"),
    recommendationIfAbsent: "Detail all bibliographic databases searched along with search date coverage limits.",
  },
  {
    itemNumber: 7,
    name: "Full Search Strategy",
    section: "Methods",
    description: "Present the full search strategy for at least one database, including filters applied",
    detector: regexMatcher(/\b(search terms|search strategy|boolean operators|mesh terms|keywords used)\b/i, "methods"),
    recommendationIfAbsent: "Provide the complete search string with Boolean operators for at least one major database.",
  },
  {
    itemNumber: 8,
    name: "Selection & Screening Process",
    section: "Methods",
    description: "Specify the methods used to decide whether a study met inclusion criteria (e.g., dual screening)",
    detector: regexMatcher(/\b(screened independently|two reviewers|dual screening|disagreements were resolved|title and abstract screening)\b/i, "methods"),
    recommendationIfAbsent: "State whether screening was conducted independently by two or more reviewers.",
  },
  {
    itemNumber: 9,
    name: "Data Collection Process",
    section: "Methods",
    description: "Describe data extraction methods, pilot forms, and verification processes",
    detector: regexMatcher(/\b(data extraction|extracted independently|standardized form|data abstraction)\b/i, "methods"),
    recommendationIfAbsent: "Detail the data extraction process and whether independent extraction was employed.",
  },
  {
    itemNumber: 11,
    name: "Risk of Bias in Included Studies",
    section: "Methods",
    description: "Specify methods used to assess risk of bias in the included studies (RoB 2, ROBINS-I, Newcastle-Ottawa)",
    detector: regexMatcher(/\b(risk of bias|cochrane risk of bias|robins-i|quality assessment|jadad scale|newcastle-ottawa)\b/i, "methods"),
    recommendationIfAbsent: "Specify the validated assessment tool used to evaluate risk of bias in included studies.",
  },
  {
    itemNumber: 13,
    name: "Synthesis Methods & Statistical Models",
    section: "Methods",
    description: "Describe processes used to decide which studies were eligible for synthesis, models, and heterogeneity metrics",
    detector: regexMatcher(/\b(random-effects model|fixed-effect|meta-analysis|forest plot|heterogeneity|i2 statistic|pooled risk ratio|pooled odds ratio)\b/i, "methods"),
    recommendationIfAbsent: "Describe quantitative synthesis models, statistical software, and heterogeneity metrics (e.g. I^2).",
  },
  {
    itemNumber: 23,
    name: "Discussion & Review Limitations",
    section: "Discussion",
    description: "Discuss limitations of the included evidence and review processes",
    detector: regexMatcher(/\b(limitations of this review|publication bias|heterogeneity among studies|risk of bias across studies)\b/i, "discussion"),
    recommendationIfAbsent: "Discuss methodological limitations of the review process and evidence quality.",
  },
];

export const prismaGuideline: GuidelineDefinition = {
  id: "prisma",
  name: "PRISMA 2020 (Systematic Reviews & Meta-Analyses)",
  standardType: "Systematic Reviews & Meta-Analyses",
  standardVersion: "PRISMA 2020",
  standardUrl: "http://www.prisma-statement.org/",
  itemSetScope: "core_subset",
  itemSetSize: 27,
  items: PRISMA_ITEMS,
};
