import type { GuidelineDefinition, GuidelineDefinitionItem } from "./types";
import { regexMatcher } from "./utils";

export const STROBE_ITEMS: GuidelineDefinitionItem[] = [
  {
    itemNumber: 1,
    name: "Title and Abstract",
    section: "Title/Abstract",
    description: "Indicate study design with a commonly used term in title or abstract",
    detector: regexMatcher(/\b(cohort|case-control|cross-sectional|longitudinal|observational|prospective|retrospective)\b/i, "abstract"),
    recommendationIfAbsent: "Explicitly state the observational study design (cohort, case-control, cross-sectional) in the abstract.",
  },
  {
    itemNumber: 2,
    name: "Background / Rationale",
    section: "Introduction",
    description: "Explain the scientific background and rationale for the investigation",
    detector: regexMatcher(/\b(background|rationale|prior research|unclear whether|remains poorly understood|knowledge gap)\b/i, "introduction"),
    recommendationIfAbsent: "Clarify the specific scientific background and unresolved question being addressed.",
  },
  {
    itemNumber: 3,
    name: "Objectives & Hypotheses",
    section: "Introduction",
    description: "State specific objectives, including any prespecified hypotheses",
    detector: regexMatcher(/\b(we hypothesized|aim of (?:this|the) study|primary objective|we aimed to|investigate whether)\b/i, "introduction"),
    recommendationIfAbsent: "Conclude the Introduction with an explicit, formal statement of primary objectives and study hypotheses.",
  },
  {
    itemNumber: 4,
    name: "Study Design",
    section: "Methods",
    description: "Present key elements of study design early in the paper",
    detector: regexMatcher(/\b(study design|study population|study protocol|cohort design|cross-sectional design)\b/i, "methods"),
    recommendationIfAbsent: "Dedicate an early subsection in Methods defining the overarching design, timeframes, and design framework.",
  },
  {
    itemNumber: 5,
    name: "Setting & Timeline",
    section: "Methods",
    description: "Describe the setting, locations, and relevant dates, including periods of recruitment, exposure, and follow-up",
    detector: regexMatcher(/\b(conducted at|enrolled between|recruited between|between (?:19|20)\d\d and (?:19|20)\d\d|follow-up period|institutional setting)\b/i, "methods"),
    recommendationIfAbsent: "Document exact recruitment calendars, physical hospital/regional settings, and duration of follow-up observation.",
  },
  {
    itemNumber: 6,
    name: "Participants / Eligibility",
    section: "Methods",
    description: "Give eligibility criteria, sources, and methods of selection of participants",
    detector: regexMatcher(/\b(inclusion criteria|exclusion criteria|eligible (?:patients|participants|subjects)|inclusion and exclusion)\b/i, "methods"),
    recommendationIfAbsent: "Itemize formal inclusion and exclusion criteria to allow reproducibility and assess selection validity.",
  },
  {
    itemNumber: 7,
    name: "Variables & Operationalization",
    section: "Methods",
    description: "Clearly define all outcomes, exposures, predictors, potential confounders, and effect modifiers",
    detector: regexMatcher(/\b(primary outcome|secondary outcome|dependent variable|independent variable|exposure variable|covariates|confounding)\b/i, "methods"),
    recommendationIfAbsent: "Explicitly classify variables into exposures, primary/secondary outcomes, and pre-specified confounding covariates.",
  },
  {
    itemNumber: 8,
    name: "Data Sources & Measurement",
    section: "Methods",
    description: "Give sources of data and details of methods of assessment (measurement)",
    detector: regexMatcher(/\b(data source|extracted from|registry|electronic health records|questionnaire|assay|spectrometry|measurement protocol)\b/i, "methods"),
    recommendationIfAbsent: "Describe the measurement instruments, sensor models, lab assays, or clinical registry extraction protocols.",
  },
  {
    itemNumber: 9,
    name: "Bias Mitigation",
    section: "Methods",
    description: "Describe any efforts to address potential sources of bias",
    detector: regexMatcher(/\b(selection bias|information bias|recall bias|confounding by indication|propensity score|matching)\b/i, "methods"),
    recommendationIfAbsent: "Explicitly discuss mechanisms used to prevent or adjust for selection, reporting, and confounding biases.",
  },
  {
    itemNumber: 10,
    name: "Study Size Determination",
    section: "Methods",
    description: "Explain how the study size was arrived at",
    detector: regexMatcher(/\b(sample size calculation|power calculation|power analysis|sample of \d+|enrolled \d+|convenience sample)\b/i, "methods"),
    recommendationIfAbsent: "Report formal statistical power analysis or statistical justification for the achieved cohort volume.",
  },
  {
    itemNumber: 11,
    name: "Quantitative Variables",
    section: "Methods",
    description: "Explain how quantitative variables were handled in the analyses (groupings, categories)",
    detector: regexMatcher(/\b(dichotomized|categorized|tertiles|quartiles|continuous variables|median split)\b/i, "methods"),
    recommendationIfAbsent: "State whether continuous variables were analyzed linearly or grouped into percentiles/categories.",
  },
  {
    itemNumber: 12,
    name: "Statistical Methods",
    section: "Methods",
    description: "Describe all statistical methods, including those used to control for confounding and missing data",
    detector: regexMatcher(/\b(multivariable regression|logistic regression|cox proportional|multiple imputation|sensitivity analysis|subgroup analysis)\b/i, "methods"),
    recommendationIfAbsent: "Specify multivariable regression parameters, missing data handling, and sensitivity validation checks.",
  },
  {
    itemNumber: 13,
    name: "Participant Demographics & Numbers",
    section: "Results",
    description: "Report numbers of individuals at each stage of study (e.g. screened, eligible, confirmed, analyzed)",
    detector: regexMatcher(/\b(flow diagram|a total of \d+|of the \d+ participants|flowchart|exclusion reasons)\b/i, "results"),
    recommendationIfAbsent: "Provide exact attrition figures detailing candidate screening, exclusions, and final analytical cohort size.",
  },
  {
    itemNumber: 14,
    name: "Descriptive Cohort Characteristics",
    section: "Results",
    description: "Give characteristics of study participants (demographic, clinical, social) and information on exposures",
    detector: regexMatcher(/\b(table 1|baseline characteristics|demographic characteristics|mean age|median age)\b/i, "results"),
    recommendationIfAbsent: "Synthesize baseline cohort demographics, clinical parameters, and exposure profiles in a dedicated Table 1.",
  },
  {
    itemNumber: 15,
    name: "Outcome Data Events",
    section: "Results",
    description: "Report numbers of outcome events or summary measures over time",
    detector: regexMatcher(/\b(incident cases|events occurred|person-years|incidence rate|cumulative incidence|prevalence of)\b/i, "results"),
    recommendationIfAbsent: "State exact event tallies, incidence rates per observation period, or proportion estimates.",
  },
  {
    itemNumber: 16,
    name: "Main Results & Unadjusted/Adjusted Estimates",
    section: "Results",
    description: "Give unadjusted estimates and, if applicable, confounder-adjusted estimates and their precision (95% CI)",
    detector: regexMatcher(/\b(adjusted odds ratio|\baor\b|hazard ratio|\bhr\b|relative risk|\brr\b|95% ci|95% confidence interval|p\s*=\s*0\.\d+)\b/i, "results"),
    recommendationIfAbsent: "Provide both crude and multivariable-adjusted effect estimates accompanied by 95% confidence intervals.",
  },
  {
    itemNumber: 17,
    name: "Other Analyses (Subgroup/Sensitivity)",
    section: "Results",
    description: "Report other analyses done (e.g. analyses of subgroups and interactions, and sensitivity analyses)",
    detector: regexMatcher(/\b(sensitivity analysis|subgroup analysis|interaction term|stratified by|stratification)\b/i, "results"),
    recommendationIfAbsent: "Document sensitivity models or exploratory subgroup analyses testing stability across covariate strata.",
  },
  {
    itemNumber: 18,
    name: "Key Results Summary",
    section: "Discussion",
    description: "Summarize key results with reference to study objectives",
    detector: regexMatcher(/\b(in this study, we found|our findings demonstrate|principal finding|we observed that)\b/i, "discussion"),
    recommendationIfAbsent: "Summarize key quantitative findings in the opening paragraph of the Discussion relative to hypotheses.",
  },
  {
    itemNumber: 19,
    name: "Limitations & Confounders",
    section: "Discussion",
    description: "Discuss limitations of the study, taking into account sources of potential bias or imprecision",
    detector: regexMatcher(/\b(limitations? of (?:this|our) study|several limitations|unmeasured confounding|residual confounding|selection bias|retrospective design)\b/i, "discussion"),
    recommendationIfAbsent: "Devote a comprehensive subsection to study limitations, unmeasured confounders, and measurement errors.",
  },
  {
    itemNumber: 20,
    name: "Interpretation & Plausibility",
    section: "Discussion",
    description: "Give a cautious overall interpretation of results considering objectives, limitations, multiple analyses, and external evidence",
    detector: regexMatcher(/\b(consistent with previous|biological plausibility|mechanism underlying|contrasts with earlier|in line with)\b/i, "discussion"),
    recommendationIfAbsent: "Contextualize results within existing mechanistic literature, acknowledging contradictory evidence.",
  },
  {
    itemNumber: 21,
    name: "Generalizability / External Validity",
    section: "Discussion",
    description: "Discuss the generalizability (external validity) of the study results",
    detector: regexMatcher(/\b(generalizability|external validity|applicable to other|generalizable to|broad population)\b/i, "discussion"),
    recommendationIfAbsent: "State explicit boundary conditions and external validity limitations regarding population transferability.",
  },
  {
    itemNumber: 22,
    name: "Funding & Conflicts of Interest",
    section: "Back Matter",
    description: "Give the source of funding and the role of the funders, and declare conflicts of interest",
    detector: regexMatcher(/\b(supported by grant|financial support|conflict of interest|competing interests|no potential conflict|funding:)\b/i),
    recommendationIfAbsent: "Include formal statements disclosing research grant identifiers and author conflict of interest disclosures.",
  },
];

export const strobeGuideline: GuidelineDefinition = {
  id: "strobe",
  name: "STROBE (22-Item Observational Epidemiological Checklist)",
  standardType: "Observational Cohort, Case-Control & Cross-Sectional Studies",
  standardVersion: "STROBE Statement v4",
  standardUrl: "https://www.strobe-statement.org/",
  itemSetScope: "full",
  itemSetSize: 22,
  items: STROBE_ITEMS,
};
