import {
  CitationIntegritySummary,
  PublishedArticleDetails,
  ParsedManuscript,
} from "../types";
import { ManuscriptContext } from "./types";
import { detectPublishedArticle } from "../publication-detector";
import { computeCitationIntegrity } from "./citation-audit";

export interface IntegritySignal {
  id: string;
  category:
    | "PRIOR_PUBLICATION"
    | "CITATION_INTEGRITY"
    | "REQUIRED_STATEMENTS"
    | "SIMILARITY_PROXY"
    | "STATISTICAL_CONSISTENCY"
    | "SECURITY";
  severity: "BLOCKER" | "WARNING" | "ADVISORY";
  message: string;
  details?: Record<string, unknown>;
}

export interface IntegrityResult {
  passed: boolean;
  blockers: IntegritySignal[];
  warnings: IntegritySignal[];
  signals: IntegritySignal[];
  priorPub?: PublishedArticleDetails;
  refAudit?: CitationIntegritySummary;
  summary: string;
}

/**
 * Tortured phrases catalog (Cabanac et al. 2021):
 * Characteristic distorted expressions generated by text spinners or paper mills
 * trying to evade plagiarism detection.
 */
const TORTURED_PHRASES_CATALOG: [RegExp, string][] = [
  [/\bcounterfeit\s+consciousness\b/i, 'Spin phrase for "artificial intelligence"'],
  [/\bprofound\s+learning\b/i, 'Spin phrase for "deep learning"'],
  [/\birregular\s+timberland\b/i, 'Spin phrase for "random forest"'],
  [/\bcolossal\s+information\b/i, 'Spin phrase for "big data"'],
  [/\bneural\s+organ\b/i, 'Spin phrase for "neural network"'],
  [/\bbolster\s+vector\s+machine\b/i, 'Spin phrase for "support vector machine"'],
  [/\bmolecular\s+dynamics\s+recreation\b/i, 'Spin phrase for "molecular dynamics simulation"'],
];

/**
 * Evaluates text for paper-mill / paraphrasing artifacts.
 */
export function computeSimilaritySignals(rawText: string): IntegritySignal[] {
  const signals: IntegritySignal[] = [];
  const lower = rawText.toLowerCase();

  for (const [regex, desc] of TORTURED_PHRASES_CATALOG) {
    if (regex.test(lower)) {
      signals.push({
        id: "tortured-phrase-detected",
        category: "SIMILARITY_PROXY",
        severity: "WARNING",
        message: `Paper-mill paraphrasing artifact detected: "${rawText.match(regex)?.[0]}". ${desc}.`,
      });
    }
  }

  return signals;
}

/**
 * Evaluates mandatory journal publishing statements (Ethics, Data, COI, Contributions).
 */
export function checkRequiredStatements(manuscript: ParsedManuscript): IntegritySignal[] {
  const signals: IntegritySignal[] = [];
  const decl = manuscript.mandatoryDeclarations;

  if (!decl?.ethicsStatement?.present) {
    const isHumanOrAnimal = /patient|human|subject|trial|participant|mice|rat|animal/i.test(
      manuscript.abstract || manuscript.title
    );
    signals.push({
      id: "stmt-ethics-missing",
      category: "REQUIRED_STATEMENTS",
      severity: isHumanOrAnimal ? "WARNING" : "ADVISORY",
      message: isHumanOrAnimal
        ? "Ethics & Institutional Review Board (IRB) oversight statement missing on clinical/animal study."
        : "No explicit Ethics / Institutional Review Board statement detected.",
    });
  }

  if (!decl?.dataAvailability?.present) {
    signals.push({
      id: "stmt-data-missing",
      category: "REQUIRED_STATEMENTS",
      severity: "WARNING",
      message: "Data Availability Statement missing (mandatory for Springer Nature, Elsevier, PLOS, IEEE).",
    });
  }

  if (!decl?.competingInterests?.present) {
    signals.push({
      id: "stmt-coi-missing",
      category: "REQUIRED_STATEMENTS",
      severity: "ADVISORY",
      message: "Conflict of Interest / Competing Interests declaration missing.",
    });
  }

  if (!decl?.authorContributions?.present) {
    signals.push({
      id: "stmt-credit-missing",
      category: "REQUIRED_STATEMENTS",
      severity: "ADVISORY",
      message: "Author Contributions / CRediT taxonomy statement missing.",
    });
  }

  return signals;
}

/**
 * Checks internal consistency of empirical numbers, sample sizes, and p-values.
 */
export function recomputeStatisticalChecks(manuscript: ParsedManuscript): IntegritySignal[] {
  const signals: IntegritySignal[] = [];
  const raw = manuscript.rawText || "";

  // 1. Check for Confidence Interval containing point estimate where reported like: "14.2% (95% CI [16.0%, 20.0%])"
  const ciMatches = raw.matchAll(/(-?\d+\.?\d*)\s*(?:%|\w*)?\s*\(95%\s*CI\s*[\(\[]\s*(-?\d+\.?\d*)\s*(?:%|\w*)?\s*,\s*(-?\d+\.?\d*)/gi);
  for (const m of ciMatches) {
    const est = parseFloat(m[1]);
    const lower = parseFloat(m[2]);
    const upper = parseFloat(m[3]);
    if (!isNaN(est) && !isNaN(lower) && !isNaN(upper)) {
      if (est < lower || est > upper) {
        signals.push({
          id: "stat-ci-inconsistent",
          category: "STATISTICAL_CONSISTENCY",
          severity: "WARNING",
          message: `Inconsistent Confidence Interval: Reported point estimate (${est}) falls outside 95% CI [${lower}, ${upper}].`,
        });
      }
    }
  }

  // 2. Check for contradictory claims: "not statistically significant (p < 0.001)" or "statistically significant (p = 0.45)"
  if (/statistically\s+significant[^\.\n;]{0,40}p\s*>\s*0\.05/i.test(raw)) {
    signals.push({
      id: "stat-significance-contradiction",
      category: "STATISTICAL_CONSISTENCY",
      severity: "WARNING",
      message: 'Claim of statistical significance contradicts reported p-value threshold (p > 0.05).',
    });
  }

  return signals;
}

/**
 * Master Stage 0 Technical Completeness & Integrity Screening Gate.
 * Runs before Stage 1 editorial triage:
 * 1. Checks prior publication (Crossref/OpenAlex), permitting preprints.
 * 2. Checks academic document eligibility.
 * 3. Audits prompt injection & sanitized payloads.
 * 4. Checks required statements (Ethics, Data, COI).
 * 5. Runs similarity proxies (tortured phrases).
 * 6. Checks internal statistical consistency.
 * 7. Analyzes citation retractions and unverified references.
 */
export async function runIntegrityGate(
  ctx: ManuscriptContext,
  preloadedPub?: PublishedArticleDetails,
  preloadedCitations?: CitationIntegritySummary
): Promise<IntegrityResult> {
  const signals: IntegritySignal[] = [];
  const manuscript = ctx.manuscript;

  // 1. Prior publication check
  const priorPub = preloadedPub || (await detectPublishedArticle(manuscript.rawText, manuscript.title));
  if (priorPub?.isPublished && !priorPub.isPreprint) {
    signals.push({
      id: "prior-pub-blocker",
      category: "PRIOR_PUBLICATION",
      severity: "BLOCKER",
      message: `Manuscript appears already published in ${priorPub.journalName || "a peer-reviewed venue"} (DOI: ${priorPub.doi || "detected"}).`,
      details: { doi: priorPub.doi, journal: priorPub.journalName },
    });
  } else if (priorPub?.isPreprint) {
    signals.push({
      id: "preprint-permitted",
      category: "PRIOR_PUBLICATION",
      severity: "ADVISORY",
      message: `Identified preprint on ${priorPub.preprintServer || "scholarly server"}. Preprints are eligible for pre-submission evaluation.`,
    });
  }

  // 2. Non-academic classification check
  if (
    manuscript.classification &&
    !manuscript.classification.isAcademicManuscript &&
    manuscript.classification.category !== "academic_manuscript"
  ) {
    signals.push({
      id: "non-academic-blocker",
      category: "SECURITY",
      severity: "BLOCKER",
      message: `Document identified as "${manuscript.classification.categoryLabel || manuscript.classification.category}", not an academic research manuscript.`,
    });
  }

  // 3. Prompt injection detection
  if (manuscript.injectionSuspicionFlags && manuscript.injectionSuspicionFlags.length > 0) {
    signals.push({
      id: "injection-sanitized",
      category: "SECURITY",
      severity: "WARNING",
      message: `Sanitized ${manuscript.injectionSuspicionFlags.length} anomalous prompt injection / hidden text pattern(s) from document text.`,
      details: { flags: manuscript.injectionSuspicionFlags },
    });
  }

  // 4. Citation audit
  const refAudit =
    preloadedCitations ||
    computeCitationIntegrity([], manuscript.references?.length || 0, manuscript.authors);

  if (refAudit.retractedCount > 0) {
    signals.push({
      id: "citation-retracted",
      category: "CITATION_INTEGRITY",
      severity: "BLOCKER",
      message: `Fatal Integrity Hazard: Bibliography references ${refAudit.retractedCount} formally retracted paper(s). Automated editorial screeners will desk-reject.`,
    });
  }
  if ((refAudit.expressionOfConcernCount || 0) > 0) {
    signals.push({
      id: "citation-concern",
      category: "CITATION_INTEGRITY",
      severity: "WARNING",
      message: `Bibliography contains ${refAudit.expressionOfConcernCount} paper(s) under formal Expression of Concern.`,
    });
  }
  if (refAudit.unresolvableCount > 5) {
    signals.push({
      id: "citation-unresolved",
      category: "CITATION_INTEGRITY",
      severity: "WARNING",
      message: `${refAudit.unresolvableCount} references could not be verified in Crossref. Requires manual verification before submission.`,
    });
  }

  // 5. Similarity proxy (tortured phrases)
  signals.push(...computeSimilaritySignals(manuscript.rawText || ""));

  // 6. Required publishing statements
  signals.push(...checkRequiredStatements(manuscript));

  // 7. Statistical consistency
  signals.push(...recomputeStatisticalChecks(manuscript));

  // Partition signals into blockers and warnings
  const blockers = signals.filter((s) => s.severity === "BLOCKER");
  const warnings = signals.filter((s) => s.severity === "WARNING");
  const passed = blockers.length === 0;

  const summary = passed
    ? warnings.length === 0
      ? "Stage 0 Passed: Manuscript meets all baseline technical, integrity, and compliance criteria."
      : `Stage 0 Passed with ${warnings.length} advisory warning(s): Review proceeding to Stage 1 editorial triage.`
    : `Stage 0 Blocked: ${blockers.map((b) => b.message).join("; ")}`;

  return {
    passed,
    blockers,
    warnings,
    signals,
    priorPub,
    refAudit,
    summary,
  };
}
